#!/usr/bin/env bash
# Script that transfers a file from our client to a server

if [ "$#" -lt 4 ]; then
    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

TRANSFER_FILE="$1"
PATH_TO_FILE="$2"
USERNAME="$3"
PATH_TO_SSH_KEY="$4"

# Create the connection
scp -o StrictHostKeyChecking=no -i "$PATH_TO_SSH_KEY" "$PATH_TO_FILE" "$USERNAME"@"$IP":~/
