#!/usr/bin/env bash
# Install nginx and configure redirection

apt-get -y update
apt-get install -y nginx

# Create an HTML file with the content "Hello World!"
echo 'Hello World!' | sudo tee /var/www/html/index.nginx-debian.html

string_for_replacement="\\\n\tlocation = /redirect_me {\n\t\t return 301 https://www.hithub.com/maazalside/;\n\t}\n"


# Use sed to replace the configuration in the Nginx default site
sudo sed -i "15i\\$string_for_replacement" /etc/nginx/sites-available/default

# Restart Nginx to apply changes
sudo service nginx restart

