#!/usr/bin/env bash
# Displays the content of the file /etc/passwd

data="/etc/passwd"

while IFS= read -r line; do
	info_print=$(echo "$line" | awk -F: '{print $1 ":" $3 ":" $6}')
	
	echo "$info_print"
done < "$data"

