#!/usr/bin/env bash
# Tell the story of passwd

data="/etc/passwd"

while IFS= read -r username x userid groupid userinfo homedir shell; do
	echo "The user $username is part of the $groupid gang, lives in $homedir and rides $shell. $userid's place is protected by the passcode $x, more info about the user here: $userinfo"
done < "$data"
