#!/usr/bin/env bash
# print Best School 10 times and Hi

counter=1
name="Best School"

while [ $counter -le 10 ]; do
	if [ $counter -eq 10 ]; then
		echo "Hi"
	fi
        echo "$name"
        ((counter++))
done
