#!/usr/bin/env bash
# print bad luck, good luck, Best School

counter=1
name="Best School"

while [ $counter -le 10 ]; do
	if [ $counter -eq 4 ]; then
		echo "bad luck"
	elif [ $counter -eq 8 ]; then
		echo "good luck"
	else 
		echo "$name"
	fi
        ((counter++))
done
