#!/usr/bin/env bash
# print bad luck from China, bad luck from Japan, bad luck from Italy

counter=1

while [ $counter -le 20 ]; do
	case $counter in
		4)
			echo $counter
			echo "bad luck from China"
			;;
		9)
			echo $counter
			echo "bad luck from Japan"
			;;
		17)
			echo $counter
			echo "bad luck from Italy"
			;;
		*)
			echo $counter
			;;
	esac

	((counter++))
done
